### PR TITLE
Improved iterable support

### PR DESCRIPTION
**Pull request by Liamolucko**
I've changed the iterable logic to support async iteration and pair iterators, as well as including `entries()`, `keys()`, `values()`, and `forEach()`.

### CODE REVIEW

**Comment by giniedp** [comment]
sorry, i missed that pull request. But it contains more than just extensions to the logic. It touches all lines and adds semicolons. I'll add a prettier and lint config files to avoid that.

**Comment by Liamolucko** [comment]
Okay, that should be fixed now.

**Comment by giniedp** [comment]
thx. do you have a sample file where iterables are used? What specific IDL file do you transpile? Just want to understand the problem/solution before merging it.

**Comment by giniedp** [comment]
think i got one. Its about cases like these https://github.com/microsoft/TypeScript-DOM-lib-generator/blob/master/inputfiles/idl/DOM.widl#L150

i'll check the commit this evening. Thanks for your work.

**Pull request merged**
